In [43]:
# data_preprocessing_tools_notes

In [44]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [45]:
# Importing the dataset
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [46]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [47]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [48]:
# Taking Care of Missing Data

In [49]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [50]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 0.3]
 ['France' 35.0 58000.0]
 ['Spain' 0.3 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [51]:
# Encoding Categorical Data

In [52]:
# Encoding the Independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [53]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [54]:
# Decoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [55]:
# Splitting the Dataset into Training Set and Test Set 

In [56]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [57]:
print(x_train)

[[0.0 0.0 1.0 0.3 52000.0]
 [0.0 1.0 0.0 40.0 0.3]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [58]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [59]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [60]:
print(y_test)

[0 1]


In [61]:
# WE have to apply Feature Scaling AFTER we split the Dataset

In [62]:
# Feature Scaling

In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [64]:
print(x_train)

[[0.0 0.0 1.0 -2.347923855273463 -0.18969093945874616]
 [0.0 1.0 0.0 0.31624412055666135 -2.3224027162979533]
 [1.0 0.0 0.0 0.5846741433103263 0.6305875532399453]
 [0.0 0.0 1.0 0.18202910917982892 0.179434382255665]
 [0.0 0.0 1.0 -0.5561534533927496 -0.35374663799848444]
 [1.0 0.0 0.0 0.8531041660639912 0.9176850256844873]
 [0.0 1.0 0.0 0.9873191774408236 1.0817407242242256]
 [1.0 0.0 0.0 -0.01929340788541976 0.05639260835086129]]


In [65]:
print(x_test)

[[0.0 1.0 0.0 -0.3548309363275009 -0.107663090188877]
 [1.0 0.0 0.0 0.11492160349141269 0.42551793006527244]]
